# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 09:25
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('note', models.CharField(max_length=256, verbose_name='内容摘要')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='文章内容')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('count', models.IntegerField(default=0, verbose_name='点击量')),
                ('image', models.ImageField(null=True, upload_to='static/uepload/static/articles/image', verbose_name='文章封面图片')),
                ('type', models.IntegerField(default=1, verbose_name='文章状态')),
                ('feilei', models.IntegerField(default=3, verbose_name='文章的分类')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=56, verbose_name='用户用户名')),
                ('password', models.CharField(max_length=256, verbose_name='用户密码')),
                ('name', models.CharField(max_length=99, verbose_name='用户姓名')),
                ('age', models.IntegerField(default=19, verbose_name='用户年龄')),
                ('email', models.EmailField(max_length=256, verbose_name='用户邮箱')),
                ('type', models.IntegerField(default=0, verbose_name='用户级别，0普通会员，1超级管理')),
                ('headers', models.ImageField(default='static/images/headers/default.png', upload_to='static/headers/', verbose_name='用户头像')),
                ('self_info', models.CharField(default='还没有设置个性签名', max_length=256, verbose_name='用户的个性签名')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
    ]
