# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181012_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='static/articles/image', verbose_name='文章封面图片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='headers',
            field=models.ImageField(default='static/images/headers/default.png', upload_to='static/headers/', verbose_name='用户头像'),
        ),
    ]
