# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181012_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='static/articles/header_image', verbose_name='文章封面图片'),
        ),
    ]
